export const cards = [
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
    {name: 'Интерстеллар', img: 'https://pp.userapi.com/7nr4rLxjErewhe1mIlhiO_6Q3BtZcgE4EieWHg/hlhXVEy9wug.jpg', duration: '1ч 42мин'},
]